name: MEXC Report Auto

on:
  schedule:
    - cron: '0 */6 * * *'     # alle 6 Stunden
  workflow_dispatch:          # manuell startbar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository clonen
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: Report erstellen
        env:
          MEXC_KEY: ${{ secrets.MEXC_KEY }}
          MEXC_SECRET: ${{ secrets.MEXC_SECRET }}
        run: |
          python3 report.py
