name: Fetch MEXC Data

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # alle 30 Minuten

permissions:
  contents: write   # wichtig: erlaubt Commit/Push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt requests

      - name: Ensure data folder
        run: |
          mkdir -p data

      - name: Fetch from MEXC
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_API_SECRET: ${{ secrets.MEXC_API_SECRET }}
        run: |
          python scripts/fetch_mexc.py

      - name: Commit data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          git commit -m "data: update latest.json" || echo "No changes to commit"
          git push
