name: Fetch MEXC Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # alle 6 Stunden automatisch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas

      - name: Run report script
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_API_SECRET: ${{ secrets.MEXC_API_SECRET }}
        run: |
          python report.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/latest.json || true
          git commit -m "Update report data" || echo "No changes"
          git push
